name: air_scanner
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  dio: ^5.4.3+1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  google_fonts: ^6.2.1
  image_picker: ^1.1.1
  lottie: ^3.1.2
  path: ^1.9.0
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  share_plus: ^9.0.0

dev_dependencies:
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
