name: air_scanner
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  camera: ^0.11.0
  dio: ^5.4.3+1
  flutter:
    sdk: flutter
  flutter_blue: ^0.8.0
  flutter_riverpod: ^2.5.1
  image_picker: ^1.1.1
  path: ^1.9.0
  path_provider: ^2.1.3

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
